name: Django test CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Install Docker Compose
    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/v2.20.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose

    # Set up Docker Compose
    - name: Set up Docker Compose
      run: docker-compose up -d

    # Optionally wait for the service to be ready
    - name: Wait for the backend to be ready
      run: |
        docker-compose exec backend sh -c "until nc -z localhost 8000; do sleep 1; done"

    - name: Run Tests
      run: |
        docker-compose exec backend sh -c "flake8 && pytest"

    # Ensure docker-compose is shut down
    - name: Tear down Docker Compose
      run: docker-compose down
